### Functions to get odd numbers
#### Using a list from a range

In [2]:
y = range(10,50)
for each in y:
    x = each % 2
    if x != 0:
        print(f"{each} is Odd")

11 is Odd
13 is Odd
15 is Odd
17 is Odd
19 is Odd
21 is Odd
23 is Odd
25 is Odd
27 is Odd
29 is Odd
31 is Odd
33 is Odd
35 is Odd
37 is Odd
39 is Odd
41 is Odd
43 is Odd
45 is Odd
47 is Odd
49 is Odd


* working with numpy

In [3]:
import numpy as np

In [4]:
arr = np.array([(4, np.nan, 98, 26), (27, np.nan, 42, 34), (32, 7, 10, 17)])
arr

array([[ 4., nan, 98., 26.],
       [27., nan, 42., 34.],
       [32.,  7., 10., 17.]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(3, 4)

In [7]:
arr2 = np.array([(1,2,3),(2,3)])
arr2

array([(1, 2, 3), (2, 3)], dtype=object)

In [8]:
type(arr2)
arr2.shape

(2,)

In [9]:
arr3 = np.array([(1,2,3),(2,3,)])
arr3

array([(1, 2, 3), (2, 3)], dtype=object)

In [10]:
arr3.shape

(2,)

In [11]:
arr4 = np.isnan(arr)
arr4

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [ ]:
arr

In [13]:
arr5 = np.isnan(arr)
arr[arr5] = 0
arr

array([[ 4.,  0., 98., 26.],
       [27.,  0., 42., 34.],
       [32.,  7., 10., 17.]])

In [ ]:
type(np.nan)

In [ ]:
import numpy as np
arr = np.array([(4, np.nan, 98, 26), (27, np.nan, 42, 34), (32, 7, 10, 17)])
arr
arr5 = np.isnan(arr)
arr[arr5] = 0
arr
m = np.mean(arr)
print(m)
arr6 = 0(arr)
arr[arr6] = m
arr

In [ ]:
cd = [x for x in range(0,15) ]
cd